### PR TITLE
initial section for image tools

### PR DESCRIPTION
**Pull request by jronallo**
Adding a section for various image tools. Mainly includes cropping tools at this point. Some of the tools could use some work, but including them as they're what we've got right now. So ought to be revisited once we get some better tools coming online.

### CODE REVIEW

**Comment by jronallo** [comment]
Also this pull request would close:
- https://github.com/IIIF/awesome-iiif/issues/65
- https://github.com/IIIF/awesome-iiif/issues/58
- https://github.com/IIIF/awesome-iiif/issues/47

**Comment by srabun** [comment]
+1

**Comment by tristanr-cogapp** [comment]
👍

**Comment by regisrob** [comment]
:+1:

**Pull request merged**
