### PR TITLE
Add link to a DHtech Workshop

### PR DESCRIPTION
**Pull request by regisrob**

### CODE REVIEW

**Comment by hadro** [comment]
👍🏼

**Comment by triplingual** [comment]
The copyeditor part of my brain notes that the new text does not end with a period, while the existing items in the section do. There are other standardization issues in the greater list, so I don't know if this PR has to have this kind of consistency before merging.

**Comment by regisrob** [comment]
I think it is not blocking, and as you said there are other irregularities in the list.

**Comment by julsraemy** [comment]
But yes @triplingual, there are irregularities that we should check, I can make a PR.

**Pull request merged**
