### PR TITLE
 Tutorial Mirador Viewer

### PR DESCRIPTION
**Pull request by ValerieAdriaens**
I added a tutorial that explains all the features of the Mirador Viewer. For that I made a new subcategory under 'Tutorial' because only technical tutorials existed.

### CODE REVIEW

**Comment by srabun** [comment]
We might want to add more Mirador tutorials if we are going to have a section for them? 👍

**Comment by julsraemy** [comment]
It'd be great to have a Mirador section I reckon but don't have they started their own Awesome repo?

**Comment by jronallo** [comment]
Agreed with @julsraemy that having product specific tutorials live with the project would be better. The community for that project/product could then better evaluate resources. Is your concern @julsraemy  one that would block including it now?

At the same time many currently associate IIIF with products like Mirador and UV, so my inclination is to add it for now. :+1: 

I would prefer it just go under the Tutorials section for now. If that's OK, then we could update the pull request appropriately.

**Comment by srabun** [comment]
There is also now the Awesome-Mirador list, perhaps we should try to include it there and then link to that? Or include in both places. But definitely link. https://github.com/ProjectMirador/mirador-awesome

**Comment by julsraemy** [comment]
@jronallo I am afraid that we may have too may duplicates between the two Awesome repos (a few are okay I guess). 

For this Mirador tutorial, I would actually prefer to include it in the Tutorial Section. But I am fine to create a dedicated Mirador section. 

Either way, we should also have a link to the Awesome Mirador list.

**Comment by julsraemy** [comment]
*too many

**Comment by jronallo** [comment]
A couple of us of discussed this on the curators Slack channel and decided to direct things like this to the Awesome Mirador list: https://github.com/ProjectMirador/mirador-awesome
I also checked in the Mirador channel and they'd accept resources like this there. 

I'm going to to leave this request open until we get this included in the Mirador list.

**Comment by jronallo** [comment]
Now included on the awesome Mirador list so closing this.

**Pull request closed without merging**
