### PR TITLE
presentation manifest tools section with a couple tools

### PR DESCRIPTION
**Pull request by jronallo**
Adding a new section for Presentation manifest tools and including a couple tools. This closes https://github.com/IIIF/awesome-iiif/issues/46 and https://github.com/IIIF/awesome-iiif/issues/64

### CODE REVIEW

**Comment by srabun** [comment]
👍

**Comment by julsraemy** [comment]
+1! :)

**Comment by emmastanford** [comment]
👍

**Comment by tristanr-cogapp** [comment]
👍

**Comment by regisrob** [comment]
:+1:

**Pull request merged**
