### PR TITLE
Added fun projects

### PR DESCRIPTION
**Pull request by cmahnke**

### CODE REVIEW

**Comment by caitlinPerry** [comment]
@cmahnke, I can't get the wallpaper demo to load on the newest version of Chrome

**Comment by cmahnke** [comment]
@caitlinPerry: That's odd. There has been a small bug with the fallback for non-HDR capable browsers, but I fixed this. Does the HDR check pass? Green text on the right.
Bildschirmfoto 2024-08-20 um 16 23 29

**Comment by caitlinPerry** [comment]
Hmmm...now the viewer is working, but the HDR check is still failing. (I have absolutely no idea how the colors could be _brighter_ than what I'm currently seeing!). Maybe another Awesome list contributor could check: @glenrobson, @triplingual, or @julsraemy?

**Comment by cmahnke** [comment]
@caitlinPerry: Great!
For HDR to work you need the appropriate Hardware, like a Apple Silicon based computer. On windows you might need to enable HDR before using it (given that your hardware supports it).
@gregbenz is an advocate HDR photography and is very active in this field, he has a page dedicated to the topic: https://gregbenzphotography.com/hdr/
It provides many non-IIIF related examples and also hints on required hardware and settings.

**Comment by gregbenz** [comment]
@cmahnke Not sure I understand your image above (appears to be a standard SDR PNG, no gain map or HDR content). Is Awesome IIIF adding support for transcoding/viewing HDR? Does that include gain maps (Adobe/Google spec or ideally upcoming ISO 21496-1)?

@caitlinPerry I have several tests on my page to confirm HDR, as well as demonstrate it on devices which have the required hardware, software, and configuration: https://gregbenzphotography.com/hdr/#tests. In short, new HDR displays offer greatly expanded peak brightness (while preserving deep blacks) in order to display photo / video content which much more accurately recreates real world light (much more colorful sunsets, city lights that truly glow, etc). HDR displays only use the full brightness when showing content encoded to use it (for example, you can create an image with whites that are much brighter than the white background of this webpage, as non-image/video content is generally limited to standard white).

As Christian suggests, HDR support is disabled by default on Windows (even if you have the required hardware). The e-book on my page has detailed information to troubleshoot setup if you have questions, but most likely you just need to go to Windows display settings and turn on the HDR toggle if you have a supporting monitor (but may need to turn off any display mirroring, reduce refresh rate, use a different HDMI dongle, etc in some cases to get the option).

**Comment by cmahnke** [comment]
@gregbenz: This pull request is about including a link to this blog post:
It's a tiled HDR image...

**Comment by gregbenz** [comment]
@cmahnke I don't see an external post reference here

**Comment by cmahnke** [comment]
Sorry, my bad:

https://christianmahnke.de/en/post/hdr-iiif/

**Comment by gregbenz** [comment]
@cmahnke Gotcha, that works as expected on Brave, fails as expected on Firefox (unsupported browser).

**Comment by triplingual** [comment]
As a side thing, the negative result of the HDR check should get a change:
"Cromium-based Chromium browser, like" ==> "Chromium-based browser like"

**Comment by cmahnke** [comment]
@triplingual : Thanks for pointing this out, I've changed it.

**Comment by cmahnke** [comment]
Just a small update: Everyone knowing to have a working HDR setup but didn't get the example to work: I was under the misconception, that Chrome enabled this feature by default in June - this isn't the case.
**One needs to enable the `enable-experimental-web-platform-features` flag in Chrome, I've updated the page.**

**Comment by julsraemy** [comment]
Is it good to merge?

**Review by julsraemy — APPROVED** [review]
Good to merge

**Pull request merged**
