### PR TITLE
added more blogs

### LINKED ISSUE #60: list of blogs
I recently started trying to keep track of the various blogs going up related to IIIF: https://docs.google.com/document/d/1qMcgC6aRaRDbzZb7FHDuPHb3j9fdrRdWdzJXzkY9GQM/edit?usp=sharing

I haven't had a chance to read any of them yet

### PR DESCRIPTION
**Pull request by srabun**
added a handful of blogs - thinking this closes #60 but then we can do separate issues for additional individual blogs moving forward, and @jronallo I wasn't sure if you wanted to include any or all of your writings on IIIF, we can make a separate issue.

### CODE REVIEW

**Comment by jronallo** [comment]
I've got some other posts in the works and then I'll submit a separate pull request that links to the tag of multiple blog posts.

**Comment by julsraemy** [comment]
I have got a couple of links that I found for my bachelor's thesis. I will give you a list of the ones I read and liked.

**Comment by jronallo** [comment]
@julsraemy Can you open a new issue or pull request with those links?

**Comment by julsraemy** [comment]
👍

**Comment by emmastanford** [comment]
+1

**Pull request merged**
