### PR TITLE
Add section on DAMs that support IIIF

### PR DESCRIPTION
**Pull request by mejackreed**
I couldn't find this information centrally located anywhere so I propose this be added to the awesome list. It would be great for potential IIIF adopters to know about existing vendor/open source support in DAMs.

### CODE REVIEW

**Comment by julsraemy** [comment]
Good idea Jack!

**Comment by janvonde** [comment]
If this gets merged I would propose to move the Goobi viewer to this section, too.

**Comment by abollini** [comment]
In this regard, I would like to point out that at 4Science we have developed a IIIF Image Viewer add on for DSpace
https://www.4science.it/en/iiif-image-viewer/

Below are some examples of the implementation of this add-on:

National Library of Naples (Italy)
https://dl.bnnonline.it/explore?bitstream_id=4206&handle=20.500.12113/53&provider=iiif-image#?c=0&m=0&s=0&cv=10&xywh=-4004%2C-1%2C16533%2C6358

University of Coimbra (Portugal) https://am.uc.pt/bib-geral/item/44239

Institute for Advanced Study (US)
https://albert.ias.edu/bitstream/handle/20.500.12111/7814/IG_II2_1646_Rotation1_300dpi.jpg?sequence=1&isAllowed=y

**Comment by glenrobson** [comment]
Just for info I think we should also have a list of supporting vendors on the iiif.io website.

**Comment by mejackreed** [comment]
This is all great info! How can we help move this forward?

**Pull request merged**
