### PR TITLE
Add vHMML to implementations

### PR DESCRIPTION
**Pull request by jrmeyerhofer**
vHMML (https://www.vhmml.org)

### CODE REVIEW

**Comment by jronallo** [comment]
@jrmeyerhofer I get a "secure connection failed" error with the https://www.vhmml.org URL. If you fix that I can merge.

**Comment by jrmeyerhofer** [comment]
Wow, that's strange as that's our website's URL. I know we were getting a new cert. last week, maybe that messed with the connection. Can you try it again? Thanks.

**Comment by jronallo** [comment]
Work now. Yes, may have just been a glitch. Merging now.

**Comment by jrmeyerhofer** [comment]
Thanks!

**Pull request merged**
