### PR TITLE
Adding links to "Writing"

### PR DESCRIPTION
**Pull request by julsraemy**
Adding a conference paper and two blog posts to readme.md

### CODE REVIEW

**Comment by emmastanford** [comment]
I have reservations about the webmentions blog post. It's really interesting, of course, but it might be worth dividing the "Writing" section into "Introductions to IIIF" (which the other links could probably fall under), "News and Press Releases" (if we want to add news articles about new adopters etc.), and something like "New Developments and Ideas", where explorations of technical possibilities like this could go. (I don't like the name "New Developments and Ideas", but you get the idea.) Anyone else have thoughts?

**Comment by julsraemy** [comment]
Right @emmastanford, I see your point about the Webmentions pos and I also think it'd be a good idea to divide the Writing sections.

**Comment by emmastanford** [comment]
Unless that's just overcomplicating things--maybe we can just arrange them by subject without dividing them into different groups. I also rounded up a few blog posts etc. a while ago, so I'll take another look at them and see if any of them are new to this list. Maybe once we have more, we can figure out how best to divide them.

**Comment by julsraemy** [comment]
I changed the pull request by removing the Webmentions article, leaving the Archiving Conference paper and the Europeana blog post.

**Comment by srabun** [comment]
@emmastanford I like the idea of categories for the writings, but also hard to do until we have more. I already added the Europeana blog in https://github.com/IIIF/awesome-iiif/pull/71 and then the only thing @julsraemy is that we are just including the title/link, and a short description - we don't need to include authors or other info since people can see those things when they click on the link.

**Comment by julsraemy** [comment]
@srabun All right, I won't go into too much detail detail then. I will also remove the Europeana post.
Shall I close this request though?

**Comment by julsraemy** [comment]
ping @jronallo ;)

**Comment by jronallo** [comment]
:+1: For adding the link from the current pull request. I'll wait until one other person looks at the current pull request before merging.

Yes, let's get an unmanageably long list of writing in the IIIF community and then we can consider how to approach it! :smile:

**Comment by regisrob** [comment]
👍

**Pull request merged**
