### PR TITLE
Added Micrio references

### PR DESCRIPTION
**Pull request by marcelduin**

### CODE REVIEW

**Comment by saracarl** [comment]
Since Micrio is a service, rather than software others can use, we should think harder about which categories this goes into.  

@hadro mentions a community call that Micrio was presented at.  Maybe add a link to that as well?

**Comment by seesmith** [comment]
Add a Guided Viewing/Storytelling title and move to under this heading.

**Comment by saracarl** [comment]
Discussing adding a "storytelling" section.  Include Micrio, CogApp's Stories, Digirati's thing for the V&A, and NCState (Niqui O'Neil's) project.

**Comment by saracarl** [comment]
@tomcrane Can you provide a link to your storytelling software?  Thanks.

**Comment by stephenwf** [comment]
@saracarl https://www.npmjs.com/package/@canvas-panel/full-page-plugin

**Comment by hadro** [comment]
Here's a link to @dnoneill's story board viewer that I think would be a good fit: https://ncsu-libraries.github.io/iiif-annotation/storyboard/

**Comment by hadro** [comment]
Per Outreach meeting 5/26, we suggest creating new section on "Storytelling" and including at least the following projects: 

- Canvas Panel plug
- Cogapp Storiiies 
- Micrio
- Annona Storyboard viewer

@seesmith has volunteered to give this a shot

**Comment by marcelduin** [comment]
Hi all, this PR has been open for quite some time, my apologies for letting this hang for so long.


> Since Micrio is a service, rather than software others can use, we should think harder about which categories this goes into.
> 
> @hadro mentions a community call that Micrio was presented at. Maybe add a link to that as well?

Micrio is both a IIIF server service, but also has an client viewer that supports independent IIIF services.

In this PR I've added it to:

* **Image servers**: it's indeed not a standalone downloadable server application, rather a hosted IIIF service. But since there is no category of hosted services yet, it would help people to list it here?

* **Image viewers**: it has a stand-alone viewer library that can display any IIIF material (demo at https://micr.io/iiif/image-api)

* **Presentation API libraries**: The Micrio service supports Presentation API 2.1: https://micr.io/iiif/presentation-api 

* **CMS Integration**: Micrio has a server API for processing new images and embedding the IIIF images in your own site.

Please advice any changes you would like to see so this PR can be merged :)

**Comment by marcelduin** [comment]
Outdated

**Pull request closed without merging**
