### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by jbhoward-dublin**
Added stand-alone version of UCD cropping/image manipulation tool (IIIF-imageManipulation) to Image Tools.

### CODE REVIEW

**Comment by srabun** [comment]
👍

**Comment by julsraemy** [comment]
👍

**Comment by regisrob** [comment]
👍

**Comment by jronallo** [comment]
I prefer this link to the code with examples that link into the demo. So I fixed the merge conflict by using the URL from this pull request rather than the previous link which was just to a demo.

**Pull request merged**
