### PR TITLE
Update implementations.md

### PR DESCRIPTION
**Pull request by altomator**
Fixing the IIIF URL page on api.bnf.fr

### CODE REVIEW

**Comment by hadro** [comment]
I will go ahead and merge this since it's an update/typo fix, but looking at the Altomator site, I would encourage you to consider adding that to the primary Awesome IIIF list, I think that kind of sequential progression of IIIF capabilities could be incredibly illuminating for folks relatively new to IIIF

**Comment by altomator** [comment]
Hi Josh,

Where do you exactly advice me to insert our IIIF demos?

Kind regards,

JP

Le mar. 16 mars 2021 à 18:05, Josh Hadro ***@***.***> a
écrit :

**Comment by hadro** [comment]
Hi @altomator, my thinking was that this aggregation of IIIF-related uses and user interfaces using Gallica content might fit under the "Experiments and fun" section:
https://github.com/IIIF/awesome-iiif#experiments-and-fun
But I think a case could also be made that it might almost fit under tutorials:
https://github.com/IIIF/awesome-iiif#tutorials
What do you think?

**Comment by altomator** [comment]
Hi Josh,

Finally, I added the link under the Tutorials section.
https://github.com/altomator/awesome-iiif#tutorials

Is this ok?

Best,

J-P

Le mar. 16 mars 2021 à 21:23, Josh Hadro ***@***.***> a
écrit :

**Comment by hadro** [comment]
Yes, looks just right, sorry for the delay but the PR should be approved
very soon

**Pull request merged**
