### PR TITLE
Intermediate alphabetical sorting

### PR DESCRIPTION
**Pull request by triplingual**
I was having trouble reading the list and propose sorting sections alphabetically, case-insensitively, that are not otherwise ordered intentionally. I recognise that #149 talks about intentional ordering in all sections. This PR makes the list more readable, but may conflict with the discussion there.

### CODE REVIEW

**Comment by triplingual** [comment]
(In case you saw this in its strange incomplete state: I'm trying to learn to use the `hub` CLI utility and forgot to quotate the title and description strings.)

**Comment by julsraemy** [comment]
Seems like a good idea, what do you think @regisrob, @jronallo ?

**Comment by regisrob** [comment]
It is indeed the most neutral way of organizing lists. It conflicts with what is proposed in #149, even if I think it would be quite delicate to curate the list this way (i.e by making recommandations on the "preferred" items in each sub-list): in my opinion it is too subjective, too dependent on the user's standpoint... Btw it is not applicable to all sections, and it also makes the awesome-iiif list harder to curate and maintain.
So I think @triplingual's proposal does not hurt.
If we do that, we should consider updating the contribution guidelines (which states that new items should be added to the end of the list).

**Comment by jronallo** [comment]
I was initially opposed to alphabetical ordering as I feel like part of the task is to provide some recommendations through ordering. But if others like the alphabetical ordering I can be swayed by the argument about saving time in managing the list.

While it hadn't been followed all of the time, generally the most recent entries were added to the end of any sub-list. That doesn't get to recommendations, but does give some sense of how long something has been around which can factor into decisions. But even then that can be independently verified and considered (or not) in anyone's own evaluative rubric for making decisions about what to try. And the community is available for recommendations as well.

If we go alphabetical, I'd like to see a note at the top of the list stating that is the ordering principle and, if it would be alright, also state that ordering is in no way indicative of a recommendation. The guidelines for pull requests should also be updated at the same time as this pull request is merged (or shortly after) to ask that new entries be inserted in alphabetical order by name.

**Comment by triplingual** [comment]
The recommendation bit is indeed tricky. Is there a way the official list maintainers could agree on an icon to indicate recommended status? Could be put at the top of the list, e.g. “✅ = recommended”. With that, order will matter a little less. It’s going to get non-alphabetical sooner or later, whether through neglect or accident, so I feel like some sort of recommendation icon would be useful whatever the outcome of this PR.

Having the last item be the most recent gives a relative duration indicator, but not a terribly meaningful one IMO. Bottom is bottom, whether the preceding ones were added 5 minutes or 5 months ago. If there were a way to automate adding a Date Added stamp, ordering by recency could be handy. Otherwise, as a consumer of this list I found the existing order to be a mild hindrance.

**Comment by hadro** [comment]
I've opened up #335 to continue the discussion around highlights/recommendation etc., but I'd like to propose we go ahead with @triplingual's PR here to reorder the sub-lists by alpha sort and not let that block the other discussion, given that the way things are being contributed to the list now is not necessarily following any best practice. 

> If we go alphabetical, I'd like to see a note at the top of the list stating that is the ordering principle and, if it would be alright, also state that ordering is in no way indicative of a recommendation. The guidelines for pull requests should also be updated at the same time as this pull request is merged (or shortly after) to ask that new entries be inserted in alphabetical order by name.

I also agree with @jronallo's comment here, so I will see if I can do a quick addition to address these elements.

**Comment by triplingual** [comment]
In the interim, I'll update this from the upstream IIIF repo to make sure I have additions since I originally put this in.

**Comment by hadro** [comment]
Thanks, Trip! I'm not good enough at git to figure out how to merge this into your branch, but here's a suggested updated bit of language for the disclaimer: 
> **Disclaimer**: The lists below are presented in alphabetical order within each section, and do not suggest any recommendation. Likewise, this list is created for informational purposes only and any links do not constitute an endorsement, recommendation, or favoring by the IIIF Consortium.

**Pull request merged**
