### PR TITLE
Added Framework Integration section, djiiif entry

### PR DESCRIPTION
**Pull request by rogerhoward**
Per issue #172 I created a new section, Framework Integration, and added a djiiif entry

I would rather use an existing section but none seemed relevant.

### CODE REVIEW

**Comment by saracarl** [comment]
So the Django integration is awesome, but the guidelines say we should have 2 items to introduce a new category.  A lot of the equivalent libraries are in the "Image Server Shims" category, not particularly appropriately.

What if we created a section called "libraries" or maybe "language support" and put djiiif as well as these two in it?:
Djatoka Ruby gem convert IIIF URLs into the URLs that Djatoka requires.
Flask-IIIF Flask extension to support IIIF in Python/Flask applications. See Flask-IIIF previewer demo and Flask-IIIF RESTful demo.

Thoughts?  From anyone, but @jronallo @glenrobson in particular?

**Comment by saracarl** [comment]
Upon further reflection, this is almost exactly the same as the Djakota Ruby gem, so maybe we should just put it under "Image Server Shims" (what djiiif is acting like in this instance) and be done with it?

**Comment by saracarl** [comment]
@rogerhoward could you move this to the "image server shims" section?  Thanks!

**Comment by julsraemy** [comment]
Ping @rogerhoward :)

**Review by julsraemy — APPROVED** [review]

**Pull request merged**
